In [ ]:
import numpy as np

In [ ]:
import numpy as np
ar=np.array(([1,2,3,4,5]),dtype=float)
print(ar)



[1. 2. 3. 4. 5.]


In [ ]:
zeros_ar=np.zeros((3,3),dtype=int)
print(zeros_ar)
ones_ar=np.ones((2,2),dtype=int)
print(ones_ar)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]


In [ ]:
arange_ar=np.arange(10)
print(arange_ar)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr=np.array([1,2,3,4,5])
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
sliced_arr=arr[2:4]
print(sliced_arr)
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)
b=np.split(a,4)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
import numpy as np
data = np.loadtxt("/content/drive/MyDrive/DATASET/DAY1.txt",dtype=int)
d = np.savetxt("/content/drive/MyDrive/DATASET/DAY1.txt",data)
print(d)
print(data)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [ ]:
import numpy as np
arange_ar=np.arange(0,1000,5)
print(arange_ar)
data=np.savetxt("/content/drive/MyDrive/DATASET/DAY1a.txt",arange_ar)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
a=np.random.rand()
print(a)

0.7788315439798336


In [ ]:
a=np.random.randint(1,1000)
print(a)

571


In [ ]:
a=np.array([[1,2],[3,4]])
print(type(a))
print(a.ndim)
print(a.shape)


<class 'numpy.ndarray'>
2
(2, 2)


In [ ]:
a=np.linspace(8,20,5)
print(a)

[ 8. 11. 14. 17. 20.]


In [ ]:
arange_ar=np.arange(24).reshape(3,2,4)
print(arange_ar)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])
print(a*b)
print(a@b)
print(np.dot(a,b))

[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]
[[ 8  5]
 [20 13]]


In [ ]:
from numpy import random

In [ ]:
a=np.ones([2,3],dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))

[[1 1 1]
 [1 1 1]]
6
[3 3]
[2 2 2]


In [ ]:
a=np.floor(np.random.random([2,12]))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
a=np.ceil(np.random.random((2,12)))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([[1,4],[5,8]])
print(a)
print(a.max())
print(a.min())
print(a.max(axis=1))
print(a.max(axis=0))

[[1 4]
 [5 8]]
8
1
[4 8]
[5 8]


In [ ]:
a=np.array([[1,4],[5,8]])
print(a)
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))
print(a.cumsum())

[[1 4]
 [5 8]]
[[ 1  5]
 [ 5 13]]
[[ 1  4]
 [ 6 12]]
[ 1  5 10 18]


In [ ]:
a=np.array([[1,4,5,8]])
print(a)
print(a.cumsum())

[[1 4 5 8]]
[ 1  5 10 18]


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.resize(3,2))
print(a)
print(a.shape)

None
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
a=np.array([1,2,3,4,5,6])
print(a.resize(2,3))
b=np.array([6,5,4,3,2,1])
print(b.resize(2,3))
print(np.vstack((a,b)))235
print(np.hstack((a,b)))

None
None
[[1 2 3]
 [4 5 6]
 [6 5 4]
 [3 2 1]]
[[1 2 3 6 5 4]
 [4 5 6 3 2 1]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


-->No of rows becomes no of group
-->Column becomes rows
-->Group becomes coloumns

In [ ]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.full((2,2),4)
print(a)
print(a.itemsize)

[[4 4]
 [4 4]]
8


In [ ]:
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


here in .cross the matrix is taken in column wise so we get 1 column and 3 rows

In [ ]:
x=np.array([1.1,4.3,0.8,2.6,3.3,5.5,7.2],float)
print(np.rint(x))

[1. 4. 1. 3. 3. 6. 7.]


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,1])
print(np.true_divide(a,b))

[0.16666667 0.28571429 0.375      0.44444444 5.        ]


In [ ]:
a=np.array([1,1,2,2,3,3,4,4])
print(np.unique(a))

[1 2 3 4]


In [ ]:
a=np.array([[1,7],[2,4]])
b=np.array([[1,6],[5,8]])
print(np.union1d(a,b))
print(np.intersect1d(a,b))
print(np.setdiff1d(a,b))

[1 2 4 5 6 7 8]
[1]
[2 4 7]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)
print(np.sin(0))

10.0
0.0


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.mod(a,b))

[10  0  0  0  0 10]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.divide(a,b))

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.multiply(a,b))

[ 200  441   60  800 1250 1500]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.matmul(a,b))

4251


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[-0.36465601 -0.28495845 -0.53864718]
 [ 0.42076058  0.98728135  0.21031566]]


-->.random defines guassin distribution

In [ ]:
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[ 0.42140324 -1.91834743  1.66117905]
 [-2.04377724 -1.68948261  0.65108818]]


-->mean=sum of all elemnts/no of elements

-->scale = standard deviation
-->loc=mean

In [ ]:
x=random.binomial(n=12,p=0.5,size=10)#n=no of trails;p=probability
print(x)

[9 6 4 5 7 6 6 6 8 4]


In [ ]:
x=random.poisson(lam=2,size=10)
print(x)

[2 2 0 1 2 2 3 1 1 2]


In [ ]:
x=random.choice([1,2,3,4,5])
print(x)

4


In [ ]:
a=(random.choice([3,5],p=[0.5,0.5],size=(3,4)))
print(a)

[[5 3 5 3]
 [5 3 3 5]
 [3 3 3 3]]
